import type { ReactElement } from 'react';
import { BsDiagram3, BsRobot, BsStars } from 'react-icons/bs';
import {
  FiBox,
  FiCpu,
  FiDatabase,
  FiEdit3,
  FiGitBranch,
  FiGrid,
  FiLayers,
  FiPackage,
  FiPenTool,
} from 'react-icons/fi';
import {
  SiAntdesign,
  SiAppwrite,
  SiAxios,
  SiBabel,
  SiBun,
  SiCapacitor,
  SiCommitlint,
  SiCss,
  SiDocker,
  SiEsbuild,
  SiEslint,
  SiExpo,
  SiExpress,
  SiFirebase,
  SiFramer,
  SiGithubactions,
  SiJavascript,
  SiJest,
  SiJquery,
  SiLess,
  SiMongodb,
  SiMysql,
  SiNetlify,
  SiNextdotjs,
  SiNginx,
  SiNodedotjs,
  SiPnpm,
  SiPostcss,
  SiPostgresql,
  SiPrettier,
  SiPwa,
  SiReact,
  SiReacthookform,
  SiReactquery,
  SiRedis,
  SiRedux,
  SiSass,
  SiStorybook,
  SiStyledcomponents,
  SiStylelint,
  SiSwr,
  SiTailwindcss,
  SiTurborepo,
  SiTypescript,
  SiVercel,
  SiVite,
  SiWebpack,
} from 'react-icons/si';

export type StacksProps = {
  [key: string]: ReactElement;
};

const iconSize = 20;

const genericClassName = 'text-neutral-500 dark:text-neutral-300';

export const STACKS: StacksProps = {
  JavaScript: <SiJavascript size={iconSize} className='text-yellow-400' />,
  TypeScript: <SiTypescript size={iconSize} className='text-blue-400' />,
  CSS: <SiCss size={iconSize} className='text-blue-400' />,
  Sass: <SiSass size={iconSize} className='text-pink-400' />,
  Less: <SiLess size={iconSize} className='text-sky-500' />,
  PostCSS: <SiPostcss size={iconSize} className='text-orange-500' />,
  StyleX: <FiPenTool size={iconSize} className={genericClassName} />,
  'React.js': <SiReact size={iconSize} className='text-sky-500' />,
  'Next.js': <SiNextdotjs size={iconSize} />,
  'React Native': <SiReact size={iconSize} className='text-cyan-400' />,
  Expo: <SiExpo size={iconSize} />,
  Capacitor: <SiCapacitor size={iconSize} className='text-sky-400' />,
  'Ant Design': <SiAntdesign size={iconSize} className='text-blue-500' />,
  'shadcn/ui': <FiBox size={iconSize} className={genericClassName} />,
  TailwindCSS: <SiTailwindcss size={iconSize} className='text-cyan-300' />,
  'Styled Components': (
    <SiStyledcomponents size={iconSize} className='text-pink-500' />
  ),
  'Framer Motion': <SiFramer size={iconSize} className='text-pink-400' />,
  Redux: <SiRedux size={iconSize} className='text-purple-500' />,
  Zustand: <FiLayers size={iconSize} className={genericClassName} />,
  Jotai: <BsStars size={iconSize} className='text-violet-400' />,
  Bunshi: <BsDiagram3 size={iconSize} className='text-indigo-400' />,
  'React Query': (
    <SiReactquery size={iconSize} className='text-rose-500' />
  ),
  SWR: <SiSwr size={iconSize} className='text-emerald-400' />,
  Formily: <FiEdit3 size={iconSize} className={genericClassName} />,
  'React Hook Form': (
    <SiReacthookform size={iconSize} className='text-pink-500' />
  ),
  PWA: <SiPwa size={iconSize} className='text-amber-600' />,
  Vite: <SiVite size={iconSize} className='text-purple-500' />,
  Webpack: <SiWebpack size={iconSize} className='text-blue-500' />,
  Rspack: <FiPackage size={iconSize} className={genericClassName} />,
  Turbopack: <FiGrid size={iconSize} className={genericClassName} />,
  Rsbuild: <FiPackage size={iconSize} className={genericClassName} />,
  ESBuild: <SiEsbuild size={iconSize} className='text-yellow-500' />,
  Babel: <SiBabel size={iconSize} className='text-yellow-400' />,
  Turborepo: <SiTurborepo size={iconSize} />,
  ESLint: <SiEslint size={iconSize} className='text-purple-500' />,
  Prettier: <SiPrettier size={iconSize} className='text-pink-400' />,
  Stylelint: <SiStylelint size={iconSize} className='text-green-500' />,
  Commitlint: <SiCommitlint size={iconSize} className='text-emerald-500' />,
  Husky: <FiGitBranch size={iconSize} className={genericClassName} />,
  Jest: <SiJest size={iconSize} className='text-red-600' />,
  Playwright: <FiBox size={iconSize} className={genericClassName} />,
  Storybook: <SiStorybook size={iconSize} className='text-amber-500' />,
  'Node.js': <SiNodedotjs size={iconSize} className='text-green-600' />,
  Express: <SiExpress size={iconSize} />,
  Firebase: <SiFirebase size={iconSize} className='text-yellow-500' />,
  Appwrite: <SiAppwrite size={iconSize} className='text-pink-500' />,
  MySQL: <SiMysql size={iconSize} className='text-sky-600' />,
  PostgreSQL: <SiPostgresql size={iconSize} className='text-blue-500' />,
  MongoDB: <SiMongodb size={iconSize} className='text-green-500' />,
  Redis: <SiRedis size={iconSize} className='text-red-500' />,
  LangChain: <BsRobot size={iconSize} className='text-emerald-400' />,
  LangGraph: <BsDiagram3 size={iconSize} className='text-cyan-400' />,
  Mastra: <FiCpu size={iconSize} className={genericClassName} />,
  Pinecone: <FiDatabase size={iconSize} className='text-emerald-500' />,
  Axios: <SiAxios size={iconSize} className='text-indigo-500' />,
  Docker: <SiDocker size={iconSize} className='text-sky-500' />,
  Nginx: <SiNginx size={iconSize} className='text-green-500' />,
  Vercel: <SiVercel size={iconSize} />,
  Netlify: <SiNetlify size={iconSize} className='text-cyan-400' />,
  pnpm: <SiPnpm size={iconSize} className='text-orange-500' />,
  bun: <SiBun size={iconSize} className='text-amber-500' />,
  'GitHub Actions': (
    <SiGithubactions size={iconSize} className='text-blue-500' />
  ),
  jQuery: <SiJquery size={iconSize} className='text-blue-400' />,
};
