import type { Options as RehypeSanitizeSchema } from 'rehype-sanitize';

type SchemaAttributes = NonNullable<RehypeSanitizeSchema['attributes']>;
type SchemaAttribute = NonNullable<SchemaAttributes[string]>[number];

const markdownTagNames: NonNullable<RehypeSanitizeSchema['tagNames']> = [
  'a',
  'b',
  'blockquote',
  'br',
  'code',
  'dd',
  'del',
  'details',
  'div',
  'dl',
  'dt',
  'em',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'hr',
  'i',
  'img',
  'input',
  'ins',
  'kbd',
  'li',
  'ol',
  'p',
  'picture',
  'pre',
  'q',
  'rp',
  'rt',
  'ruby',
  's',
  'samp',
  'section',
  'source',
  'span',
  'strike',
  'strong',
  'sub',
  'summary',
  'sup',
  'table',
  'tbody',
  'td',
  'tfoot',
  'th',
  'thead',
  'tr',
  'tt',
  'ul',
  'var',
];

const commonAttributes: SchemaAttribute[] = [
  'abbr',
  'align',
  'alt',
  'ariaDescribedBy',
  'ariaLabel',
  'ariaLabelledBy',
  'height',
  'hrefLang',
  'htmlFor',
  'itemProp',
  'lang',
  'longDesc',
  'media',
  'open',
  'readOnly',
  'rowSpan',
  'scope',
  'span',
  'src',
  'summary',
  'tabIndex',
  'title',
  'useMap',
  'vAlign',
  'value',
  'width',
];

export const feishuHtmlSanitizeSchema: RehypeSanitizeSchema = {
  tagNames: markdownTagNames,
  attributes: {
    '*': commonAttributes,
    a: ['href'],
    div: [
      'itemScope',
      'itemType',
      'column-size',
      'width-ratio',
      [
        'className',
        'callout',
        'callout-emoji',
        /^callout-bg-\d+$/,
        /^callout-border-\d+$/,
        /^callout-color-\d+$/,
      ],
    ],
    img: [
      'src',
      'alt',
      'title',
      'align',
      'longDesc',
      'src-width',
      'src-height',
    ],
    input: [
      ['disabled', true],
      ['type', 'checkbox'],
    ],
  },
  protocols: {
    cite: ['http', 'https'],
    href: ['http', 'https', 'irc', 'ircs', 'mailto', 'xmpp'],
    longDesc: ['http', 'https'],
    src: ['http', 'https'],
  },
};

export const commentHtmlSanitizeSchema: RehypeSanitizeSchema = {
  tagNames: [
    'a',
    'blockquote',
    'br',
    'code',
    'del',
    'em',
    'li',
    'ol',
    'p',
    'pre',
    'strong',
    'ul',
  ],
  attributes: {
    a: ['href'],
  },
  strip: ['iframe', 'script', 'style'],
  protocols: {
    href: ['http', 'https', 'mailto'],
  },
};
